Update ssr-switch

diff --git a/package/lean/luci-app-ssr-plus/root/usr/bin/ssr-switch b/package/lean/luci-app-ssr-plus/root/usr/bin/ssr-switch
--- a/package/lean/luci-app-ssr-plus/root/usr/bin/ssr-switch
+++ b/package/lean/luci-app-ssr-plus/root/usr/bin/ssr-switch
@@ -15,16 +15,6 @@ server_count=0
 NAME=shadowsocksr
 ENABLE_SERVER=nil
 CONFIG_SWTICH_FILE=/var/etc/${NAME}_t.json
-logfile="/tmp/ssrplus.log"
-
-clean_log(){
-	logrow=$(grep -c "" ${logfile})
-	if [ $logrow -ge 500 ];then
-		cat /dev/null > ${logfile}
-		echo "$LOGTIME Log条数超限，清空处理！" >> ${logfile}
-	fi
-}
-
 
 [ -n "$1" ] && cycle_time=$1
 [ -n "$2" ] && switch_time=$2
@@ -44,36 +34,42 @@ CURRENT_SERVER=$DEFAULT_SERVER
 
 #判断代理是否正常
 check_proxy() {
-	curl -sL --connect-timeout 3 "https://www.google.com"| grep google |grep -v grep| wc -l || curl -sL --connect-timeout 3 "https://www.youtube.com"| grep youtube |grep -v grep| wc -l
-	if [ "$?" == "0" ]; then
-		return 0
-	else
-		curl -sL --connect-timeout 3 "https://www.baidu.com"| grep baidu |grep -v grep| wc -l || curl -sL --connect-timeout 3 "https://www.17173.com"| grep 17173 |grep -v grep| wc -l
+	local result=0
+	local try_count=$(uci_get_by_type global switch_try_count 3)
+	for i in $(seq 1 $try_count); do
+		/usr/bin/ssr-check www.google.com 80 $switch_time 1
 		if [ "$?" == "0" ]; then
-			#goole不通baidu通则不正常
-			return 1
+			# echo "$(date "+%Y-%m-%d %H:%M:%S") Check Google Proxy Success, count=$i" >> /tmp/ssrplus.log
+			result=0
+			break
 		else
-			return 2
+			# echo "$(date "+%Y-%m-%d %H:%M:%S") Check Google Proxy Fail, count=$i" >> /tmp/ssrplus.log
+			/usr/bin/ssr-check www.baidu.com 80 $switch_time 1
+			if [ "$?" == "0" ]; then
+				result=1
+			else
+				result=2
+			fi
 		fi
-	fi
-	return 0
+		sleep 1
+	done
+	return $result
 }
 
 test_proxy() {
 	local servername=$(uci_get_by_name $1 server)
 	local serverport=$(uci_get_by_name $1 server_port)
 	ret=$(ping -c 3 $servername | grep 'loss' | awk -F ',' '{ print $3 }' | awk -F "%" '{ print $1 }')
-	[ -z "$ret"  ] && return 1
+	[ -z "$ret" ] && return 1
 	[ "$ret" -gt "50" ] && return 1
 	ipset add ss_spec_wan_ac $servername 2>/dev/null
 	ret=$?
 	/usr/bin/ssr-check $servername $serverport $switch_time
 	local ret2=$?
-	if [ "$ret" = "0" ] ;then
+	if [ "$ret" == "0" ]; then
 		ipset del ss_spec_wan_ac $servername 2>/dev/null
 	fi
-	
-	if [ "$ret2" = "0" ] ;then
+	if [ "$ret2" == "0" ]; then
 		return 0
 	else
 		return 1
@@ -82,29 +78,28 @@ test_proxy() {
 
 search_proxy() {
 	let server_count=server_count+1
-	[ "$normal_flag" = "1" -a "$server_count" -le "$server_locate" ] && return 0
-	[ "$(uci_get_by_name $1 switch_enable)" != "1"  ] && return 1
+	[ "$normal_flag" == "1" -a "$server_count" -le "$server_locate" ] && return 0
+	[ "$(uci_get_by_name $1 switch_enable)" != "1" ] && return 1
 	[ $ENABLE_SERVER != nil ] && return 0
-	[ "$1" = "$CURRENT_SERVER" ] && return 0
+	[ "$1" == "$CURRENT_SERVER" ] && return 0
 	local servername=$(uci_get_by_name $1 server)
-	local serverport=$(uci_get_by_name $1 server_port)	
+	local serverport=$(uci_get_by_name $1 server_port)
 	ipset add ss_spec_wan_ac $servername 2>/dev/null
 	ret=$?
 	/usr/bin/ssr-check $servername $serverport $switch_time
 	local ret2=$?
-	if [ "$ret" = "0" ] ;then
+	if [ "$ret" == "0" ]; then
 		ipset del ss_spec_wan_ac $servername 2>/dev/null
 	fi
-	
-	if [ "$ret2" = "0" ] ;then
+	if [ "$ret2" == "0" ]; then
 		server_locate=$server_count
 		ENABLE_SERVER=$1
 		return 0
 	else
 		return 1
 	fi
-}
 
+}
 #选择可用的代理
 select_proxy() {
 	config_load $NAME
@@ -122,60 +117,52 @@ switch_proxy() {
 
 start() {
 	#不支持kcptun启用时的切换
-	[ $(uci_get_by_name $DEFAULT_SERVER kcp_enable) = "1"  ]  && return 1
+	[ $(uci_get_by_name $DEFAULT_SERVER kcp_enable) = "1" ] && return 1
 
-while [ "1" = "1" ]  #死循环
-do 
-sleep $cycle_time
-
-    clean_log
-
-	#判断当前代理是否为缺省服务器
-	if [ "$CURRENT_SERVER" != "$DEFAULT_SERVER" ] ;then
-		#echo "not default proxy"
-		echo "$(date "+%Y-%m-%d %H:%M:%S") Current server is not default Main server, try to switch back." >> ${logfile}
-
-		#检查缺省服务器是否正常
-		if test_proxy $DEFAULT_SERVER  ;then
-			#echo "switch to default proxy"
-			echo "$(date "+%Y-%m-%d %H:%M:%S") Main server is avilable." >> /tmp/ssrplus.log
-
-			#缺省服务器正常，切换回来
-			CURRENT_SERVER=$DEFAULT_SERVER
-			switch_proxy $CURRENT_SERVER 
-			echo "switch to default ["$(uci_get_by_name $CURRENT_SERVER server)"] proxy!"  >> ${logfile}
-			continue
-		else
-			echo "$(date "+%Y-%m-%d %H:%M:%S") Main server is NOT avilable.Continue using current server." >> ${logfile}
+	while [ "1" == "1" ]; do #死循环
+		sleep $cycle_time
+		LOGTIME=$(date "+%Y-%m-%d %H:%M:%S")
+		#判断当前代理是否为缺省服务器
+		if [ "$CURRENT_SERVER" != "$DEFAULT_SERVER" ]; then
+			#echo "not default proxy"
+			echo "$(date "+%Y-%m-%d %H:%M:%S") Current server is not default Main server, try to switch back." >>/tmp/ssrplus.log
+			#检查缺省服务器是否正常
+			if test_proxy $DEFAULT_SERVER; then
+				#echo "switch to default proxy"
+				echo "$(date "+%Y-%m-%d %H:%M:%S") Main server is avilable." >>/tmp/ssrplus.log
+				#缺省服务器正常，切换回来
+				CURRENT_SERVER=$DEFAULT_SERVER
+				switch_proxy $CURRENT_SERVER
+				echo "$(date "+%Y-%m-%d %H:%M:%S") switch to default ["$(uci_get_by_name $CURRENT_SERVER server)"] proxy!" >>/tmp/ssrplus.log
+				continue
+			else
+				echo "$(date "+%Y-%m-%d %H:%M:%S") Main server is NOT avilable.Continue using current server." >>/tmp/ssrplus.log
+			fi
 		fi
-	fi
-
-	#判断当前代理是否正常
-	check_proxy  
-	current_ret=$?
-
-	if [ "$current_ret" = "1" ] ;then
-		#当前代理错误，判断有无可用的服务器
-		#echo "current error"
-		echo "$(date "+%Y-%m-%d %H:%M:%S") Current server error, try to switch another server." >> ${logfile}
-     
-		select_proxy
-		if [ "$ENABLE_SERVER" != nil ] ;then
-			#有其他服务器可用，进行切换
-			#echo $(uci_get_by_name $new_proxy server)
-			echo "$(date "+%Y-%m-%d %H:%M:%S") Another server is avilable, now switching server." >> ${logfile}
-			CURRENT_SERVER=$ENABLE_SERVER
-			switch_proxy $CURRENT_SERVER
-			normal_flag=1
-			echo "$(date "+%Y-%m-%d %H:%M:%S") ShadowsocksR server switch OK" >> ${logfile}
+		#判断当前代理是否正常
+		check_proxy
+		current_ret=$?
+		if [ "$current_ret" == "1" ]; then
+			#当前代理错误，判断有无可用的服务器
+			#echo "current error"
+			echo "$(date "+%Y-%m-%d %H:%M:%S") Current server error, try to switch another server." >>/tmp/ssrplus.log
+			select_proxy
+			if [ "$ENABLE_SERVER" != nil ]; then
+				#有其他服务器可用，进行切换
+				#echo $(uci_get_by_name $new_proxy server)
+				echo "$(date "+%Y-%m-%d %H:%M:%S") Another server is avilable, now switching server." >>/tmp/ssrplus.log
+				CURRENT_SERVER=$ENABLE_SERVER
+				switch_proxy $CURRENT_SERVER
+				normal_flag=1
+				echo "$(date "+%Y-%m-%d %H:%M:%S") ShadowsocksR server switch OK" >>/tmp/ssrplus.log
+			else
+				switch_proxy $CURRENT_SERVER
+				normal_flag=1
+				echo "$(date "+%Y-%m-%d %H:%M:%S") Try restart current server." >>/tmp/ssrplus.log
+			fi
 		else
-			normal_flag=0 
+			normal_flag=0
+			echo "$(date "+%Y-%m-%d %H:%M:%S") ShadowsocksR No Problem." >>/tmp/ssrplus.log
 		fi
-
-	else
-		normal_flag=0 
-		echo "$(date "+%Y-%m-%d %H:%M:%S") ShadowsocksR No Problem."  >> ${logfile}
-	fi
-
-done
+	done
 }
